version: "2"

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    env_file: .env
    links:
      - redis
      - db
    ports:
      - "${EXTERNAL_PORT}:5000"
    volumes:
      - ./persists:/persists
    depends_on:
      - db
      - redis


  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql


  redis:
    image: redis:latest
    env_file: .env
    volumes:
      - ./redis:/var/lib/redis
