version: '2'

services:
  web:
    build: .
    env_file: .env
    links:
      - redis
      - db
    ports:
      - "${EXTERNAL_PORT}:5000"
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - FLASK_CONFIG=production
      - REDISTOGO_URL=redis://redis:6379
    volumes:
      - ./app:/app


  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql


  redis:
    image: redis:latest
    volumes:
      - ./redis:/var/lib/redis


  worker:
    build:
      context: .
      dockerfile: Workerfile
    env_file: .env
    links:
      - redis
      - db
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - FLASK_CONFIG=production
      - REDISTOGO_URL=redis://redis:6379
